### PR TITLE
feat: change web socket ping interval duration

### PR DESCRIPTION
**Pull request by mahbodsn**

### CODE REVIEW

**Comment by chairz** [comment]
What is the reason behind for adding pingInterval?

**Comment by mahbodsn** [comment]
> What is the reason behind for adding pingInterval?

```The websocket server will send a ping frame every 3 minutes. If the websocket server does not receive a pong frame back from the connection within a 10 minute period, the connection will be disconnected. Unsolicited pong frames are allowed.```

according to Binance documentation pingInterval should set every 3 minutes.

**Comment by mahbodsn** [comment]
@chairz

**Comment by chairz** [comment]
The server will send a ping frame. The client just have to reply with a pong. The pong reply is handled by the websocket library. You can test the websocket example files, it should run more than 3 minutes which also means that the ping-pong is handled correctly.

**Comment by mahbodsn** [comment]
> The server will send a ping frame. The client just have to reply with a pong. The pong reply is handled by the websocket library. You can test the websocket example files, it should run more than 3 minutes which also means that the ping-pong is handled correctly.

Hi, 
in my tests when you don't set ping interval explicitly socket connections drop after 3 minutes.

**Comment by chairz** [comment]
I have tested it on my end and data is still pushing through after 5 minutes. Please provide your test file along with `pom.xml`

**Comment by chairz** [comment]
https://github.com/square/okhttp/issues/5833
https://github.com/square/okhttp/pull/6730

You can take a look at these 2 links to understand more about it. tldr: OKHTTP does manages ping frame internally and replies with a pong.

**Comment by aisling-2** [comment]
Hi @mahbodsn, we're closing the PR as so far it doesn't seem to be an issue with this project directly and there's has not been new complains.

**Pull request closed without merging**
